FROM node:latest
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build
CMD ["npm", "run", "preview"]

# FROM nginx
# RUN mkdir /dist
# COPY from=0 dist/ /dist/
# COPY test-nginx.conf /etc/nginx/nginx.conf


# FROM nginx
# RUN mkdir /app
# WORKDIR /app
# ENV PATH /usr/src/app/node_modules/.bin:$PATH
# COPY ./ .
# COPY test-nginx.conf /etc/nginx/nginx.conf


# RUN npm install
# CMD ["npm", "run", "dev"]