FROM node:latest as buildstage
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install
COPY ./ .
RUN mkdir /dist
RUN npm run buildonly

FROM nginx
RUN mkdir /dist
COPY from=buildstage /dist/ /dist/
COPY nginx.conf /etc/nginx/nginx.conf